### PR TITLE
first working pipeline example

### PR DESCRIPTION
**Pull request by rjhowell44**
@Sscsmatrix please try the new `single_sci_source.py` script when you get a chance

### CODE REVIEW

**Comment by Sscsmatrix** [comment]
@rjhowell44 

I tried this with your python and my program ds_test2.py. With your code I received the following errors:

0:00:00.091005612 [331m15606[00m     0x3d7fe700 [31;01mERROR  [00m [00m                 DSL src/DslServices.cpp:529:DisplayNew:[00m  : Display name 'm' is not unique
0:00:00.091152750 [331m15606[00m     0x3d7fe700 [31;01mERROR  [00m [00m                 DSL src/DslServices.cpp:477:OverlaySinkNew:[00m  : Sink name 'm' is not unique
0:00:00.104171580 [331m15606[00m     0x3d7fe700 [31;01mERROR  [00m [00m                 DSL src/DslPipelineSourcesBintr.cpp:73:AddChild:[00m  : Source 'm' is already a child of 'sources-bin'
0:00:00.104282103 [331m15606[00m     0x3d7fe700 [31;01mERROR  [00m [00m                 DSL src/DslPipelineSourcesBintr.cpp:73:AddChild:[00m  : Source 'm' is already a child of 'sources-bin'
0:00:00.104410543 [331m15606[00m     0x3d7fe700 [31;01mERROR  [00m [00m                 DSL src/DslPipelineBintr.cpp:211:LinkAll:[00m  : Pipline has no Sink component
0:00:00.105379415 [331m15606[00m     0x3d7fe700 [33;01mWARN   [00m [00m         nvstreammux gstnvstreammux.c:2109:gst_nvstreammux_change_state:<stream_muxer>[00m error: Batch size not set
0:00:00.105723431 [331m15606[00m     0x3d7fe700 [31;01mERROR  [00m [00m                 DSL src/DslPipelineBintr.cpp:546:HandleErrorMessage:[00m  : Error message 'Batch size not set' received from 'stream_muxer'


Now for my code the error message is:

0:00:00.110008238 [336m15245[00m     0x3105b610 [31;01mERROR  [00m [00m                 DSL src/DslPipelineBintr.cpp:211:LinkAll:[00m  : Pipline has no Sink component
0:00:00.111326698 [336m15245[00m     0x3105b610 [33;01mWARN   [00m [00m         nvstreammux gstnvstreammux.c:2109:gst_nvstreammux_change_state:<stream_muxer>[00m error: Batch size not set

(python3:15245): GStreamer-CRITICAL **: 16:41:59.058: 
Trying to dispose object "sources-bin", but it still has a parent "p".
You need to let the parent manage the object instead of unreffing the object directly.

I am not sure why it says that there is no sink???

**Comment by Sscsmatrix** [comment]
@rjhowell44 
I will try and investigate the display setup.  Maybe my display is different.  I am assuming that this worked fine with your setup.

**Comment by rjhowell44** [comment]
@Sscsmatrix did you run `single_csi_source.py` and **not** `simple-example.py` ?

**Comment by rjhowell44** [comment]
@Sscsmatrix sorry. that was confusing...  `single_csi_source.py` is the file that should work for you..

**Comment by Sscsmatrix** [comment]
@rjhowell44 yes I was running single_csi_source.py

**Comment by rjhowell44** [comment]
did you rebuild the dsl-lib?

**Comment by Sscsmatrix** [comment]
@rjhowell44 yes I did that as well.  My create sink call returns success but the error message indicates that the pipeline has no sink component.  I will see what gdb has to say.

**Pull request merged**
