### PR TITLE
sample uri script

### PR DESCRIPTION
**Pull request by rjhowell44**
@Sscsmatrix first sample URI source... this (script and the previous one) should work out of the box from that location.  Let me know if not?

Ctr-l c  to quit both.

### CODE REVIEW

**Comment by rjhowell44** [comment]
Just FYI, you will see some GStreamer errors when you run the tests... which you can ignore for now... but make sure you're getting the correct test count
```
All tests passed (412 assertions in 66 test cases)
```

**Comment by Sscsmatrix** [comment]
@rjhowell44
So if I run the above script with python 2.7 stuff works.  I have been using Python3 and that is where I get the errors.

**Comment by Sscsmatrix** [comment]
@rjhowell44 Both of your scripts work with python 2.7 on my system.  I am not sure why they do not like python3.

**Comment by rjhowell44** [comment]
@Sscsmatrix  interesting, let me switch my Python... I should be on 3 as well

**Pull request merged**
